### ISSUE TITLE
Getting an Error when trying to install 

### ISSUE THREAD

**Issue by DavidGoedicke** [hlrs-vis/homebrew-tap#1]
macOS 10.14.3 (MBP mid 2018)

Linking CXX shared module ../../../../../../macosopt/lib/OpenCOVER/plugins/libOpenScenario.so
cd /tmp/covise-20190424-57113-1m2na3n/build.covise/src/OpenCOVER/plugins/drivingsim/OpenScenarioPlugin && /usr/local/Cellar/cmake/3.14.3/bin/cmake -E cmake_link_script CMakeFiles/OpenScenarioPlugin.dir/link.txt --verbose=1
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++   -march=native -std=c++11 -stdlib=libc++ -Wno-stdlibcxx-not-found -Wno-unused-command-line-argument -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -bundle -Wl,-headerpad_max_install_names  -undefined error -flat_namespace -o ../../../../../../macosopt/lib/OpenCOVER/plugins/libOpenScenario.so CMakeFiles/OpenScenarioPlugin.dir/OpenScenarioPlugin.cpp.o CMakeFiles/OpenScenarioPlugin.dir/ScenarioManager.cpp.o CMakeFiles/OpenScenarioPlugin.dir/Maneuver.cpp.o CMakeFiles/OpenScenarioPlugin.dir/Act.cpp.o CMakeFiles/OpenScenarioPlugin.dir/Entity.cpp.o CMakeFiles/OpenScenarioPlugin.dir/Condition.cpp.o CMakeFiles/OpenScenarioPlugin.dir/myFactory.cpp.o CMakeFiles/OpenScenarioPlugin.dir/FollowTrajectory.cpp.o CMakeFiles/OpenScenarioPlugin.dir/Trajectory.cpp.o CMakeFiles/OpenScenarioPlugin.dir/RouteInfo.cpp.o CMakeFiles/OpenScenarioPlugin.dir/CameraSensor.cpp.o CMakeFiles/OpenScenarioPlugin.dir/Position.cpp.o CMakeFiles/OpenScenarioPlugin.dir/ReferencePosition.cpp.o CMakeFiles/OpenScenarioPlugin.dir/Action.cpp.o CMakeFiles/OpenScenarioPlugin.dir/StartConditions.cpp.o CMakeFiles/OpenScenarioPlugin.dir/EndConditions.cpp.o CMakeFiles/OpenScenarioPlugin.dir/Event.cpp.o CMakeFiles/OpenScenarioPlugin.dir/Sequence.cpp.o CMakeFiles/OpenScenarioPlugin.dir/StoryElement.cpp.o ../../../../../../macosopt/lib/libcoOpenPluginUtil.dylib /usr/local/lib/libosgDB.dylib /usr/local/lib/libosgUtil.dylib /usr/local/lib/libosgViewer.dylib /usr/local/lib/libosgParticle.dylib /usr/local/lib/libosgText.dylib /usr/local/lib/libosgSim.dylib /usr/local/lib/libosgGA.dylib /usr/local/lib/libosgFX.dylib /usr/local/lib/libosg.dylib /usr/local/lib/libOpenThreads.dylib /usr/local/lib/libosgDB.dylib /usr/local/lib/libosgUtil.dylib /usr/local/lib/libosgViewer.dylib /usr/local/lib/libosgParticle.dylib /usr/local/lib/libosgText.dylib /usr/local/lib/libosgSim.dylib /usr/local/lib/libosgGA.dylib /usr/local/lib/libosgFX.dylib /usr/local/lib/libosgTerrain.dylib /usr/local/lib/libosgShadow.dylib /usr/local/lib/libosg.dylib /usr/local/lib/libOpenThreads.dylib /usr/local/lib/libosgTerrain.dylib /usr/local/lib/libosg.dylib /usr/local/lib/libOpenThreads.dylib /usr/local/lib/libosgTerrain.dylib /usr/local/lib/libosg.dylib /usr/local/lib/libOpenThreads.dylib /usr/local/lib/libosgTerrain.dylib /usr/local/lib/libboost_chrono-mt.dylib /usr/local/lib/libboost_program_options-mt.dylib /usr/local/lib/libboost_system-mt.dylib /usr/local/lib/libboost_thread-mt.dylib /usr/local/lib/libboost_filesystem-mt.dylib /usr/local/lib/libboost_iostreams-mt.dylib /usr/local/lib/libboost_date_time-mt.dylib /usr/local/lib/libboost_serialization-mt.dylib /usr/local/lib/libboost_regex-mt.dylib /usr/local/lib/libboost_locale-mt.dylib /usr/local/lib/libboost_atomic-mt.dylib /usr/local/lib/libxerces-c.so /usr/local/lib/libcal3d.dylib /usr/local/lib/libosgCal.dylib /usr/local/lib/libgeotiff.dylib /usr/local/lib/libgdal.dylib /usr/local/lib/libproj.dylib /usr/local/lib/libOpenCRG.a /usr/local/lib/libboost_chrono-mt.dylib /usr/local/lib/libboost_program_options-mt.dylib /usr/local/lib/libboost_system-mt.dylib /usr/local/lib/libboost_thread-mt.dylib /usr/local/lib/libboost_filesystem-mt.dylib /usr/local/lib/libboost_iostreams-mt.dylib /usr/local/lib/libboost_date_time-mt.dylib /usr/local/lib/libboost_serialization-mt.dylib /usr/local/lib/libboost_regex-mt.dylib /usr/local/lib/libboost_locale-mt.dylib /usr/local/lib/libboost_atomic-mt.dylib /usr/local/lib/libxerces-c.so /usr/local/lib/libcal3d.dylib /usr/local/lib/libosgCal.dylib /usr/local/lib/libgeotiff.dylib /usr/local/lib/libgdal.dylib /usr/local/lib/libproj.dylib /usr/local/lib/libOpenCRG.a ../../../../../../macosopt/lib/libcoTrafficSimulation.dylib ../../../../../../macosopt/lib/libcoOpenScenario.dylib ../../../../../../macosopt/lib/libcoVRML.dylib /usr/local/opt/jpeg-turbo/lib/libjpeg.dylib /usr/local/lib/libpng.dylib -framework OpenAL /usr/lib/libcurl.dylib /usr/local/opt/jpeg-turbo/lib/libjpeg.dylib /usr/local/lib/libpng.dylib -framework OpenAL /usr/lib/libcurl.dylib ../../../../../../macosopt/lib/libcoJS.a /usr/local/lib/libcal3d.dylib /usr/local/lib/libosgCal.dylib /usr/local/lib/libgeotiff.dylib /usr/local/lib/libcal3d.dylib /usr/local/lib/libosgCal.dylib /usr/local/lib/libgeotiff.dylib ../../../../../../macosopt/lib/libcoRoadTerrain.dylib /usr/local/lib/libgdal.dylib ../../../../../../macosopt/lib/libcoOpenVehicleUtil.dylib ../../../../../../macosopt/lib/libcoOpenCOVER.dylib ../../../../../../macosopt/lib/libcoOSGVRUI.dylib ../../../../../../macosopt/lib/libcoOpenVRUI.dylib ../../../../../../macosopt/lib/libcoVRBClient.dylib -framework OpenGL /usr/local/lib/libGLEW.dylib -framework OpenGL /usr/local/lib/libGLEW.dylib ../../../../../../macosopt/lib/libcoGRMsg.dylib ../../../../../../macosopt/lib/libcoQtUtil.dylib ../../../../../../macosopt/lib/libcoGPU.dylib ../../../../../../macosopt/lib/libcoNet.dylib ../../../../../../macosopt/lib/libcoConfig.dylib /usr/local/opt/qt5/lib/QtXml.framework/QtXml ../../../../../../macosopt/lib/libcoUtil.dylib -framework ApplicationServices /usr/lib/libz.dylib /usr/local/opt/openssl/lib/libssl.dylib /usr/local/opt/openssl/lib/libcrypto.dylib /usr/local/lib/libtiff.dylib /usr/local/opt/qt5/lib/QtNetwork.framework/QtNetwork /usr/local/lib/libosgDB.dylib /usr/local/lib/libosgUtil.dylib /usr/local/lib/libosgViewer.dylib /usr/local/lib/libosgParticle.dylib /usr/local/lib/libosgText.dylib /usr/local/lib/libosgSim.dylib /usr/local/lib/libosgGA.dylib /usr/local/lib/libosgFX.dylib /usr/local/lib/libosg.dylib /usr/local/lib/libOpenThreads.dylib /usr/local/lib/libosgTerrain.dylib /usr/local/lib/libosgShadow.dylib /usr/local/lib/libosgDB.dylib /usr/local/lib/libosgUtil.dylib /usr/local/lib/libosgViewer.dylib /usr/local/lib/libosgParticle.dylib /usr/local/lib/libosgText.dylib /usr/local/lib/libosgSim.dylib /usr/local/lib/libosgGA.dylib /usr/local/lib/libosgFX.dylib /usr/local/lib/libosg.dylib /usr/local/lib/libOpenThreads.dylib /usr/local/lib/libosgTerrain.dylib /usr/local/lib/libosgShadow.dylib /usr/local/lib/libOpenCRG.a /usr/local/opt/qt5/lib/QtScript.framework/QtScript /usr/local/opt/qt5/lib/QtScriptTools.framework/QtScriptTools /usr/local/opt/qt5/lib/QtCore.framework/QtCore /usr/local/lib/libboost_chrono-mt.dylib /usr/local/lib/libboost_program_options-mt.dylib /usr/local/lib/libboost_system-mt.dylib /usr/local/lib/libboost_thread-mt.dylib /usr/local/lib/libboost_filesystem-mt.dylib /usr/local/lib/libboost_iostreams-mt.dylib /usr/local/lib/libboost_date_time-mt.dylib /usr/local/lib/libboost_serialization-mt.dylib /usr/local/lib/libboost_regex-mt.dylib /usr/local/lib/libboost_locale-mt.dylib /usr/local/lib/libboost_atomic-mt.dylib /usr/local/lib/libproj.dylib /usr/local/lib/libxerces-c.so 
ld: file not found: /usr/local/opt/open-scene-graph/lib/libosg.157.dylib for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [../macosopt/lib/OpenCOVER/plugins/libOpenScenario.so] Error 1
make[1]: *** [src/OpenCOVER/plugins/drivingsim/OpenScenarioPlugin/CMakeFiles/OpenScenarioPlugin.dir/all] Error 2
make: *** [all] Error 2

**Comment by aumuell** [comment]
I suspect that the dependency `osgcal` was installed from an outdated bottle, which was linking against an older version of OpenSceneGraph (3.6.0 or so), which used .so version 157.

I removed the bottle from the formula for osgcal and bumped the version number. Hopefully, the build of COVISE now completes successfully.

**Comment by aumuell** [comment]
No bottles any more, so probably fixed.
