### ISSUE TITLE
Error when trying to install covise on Mac using Homebrew

### ISSUE THREAD

**Issue by kairzhanable** [hlrs-vis/homebrew-tap#2]
Hello. I am getting an error while trying to install covise from hlrs-vis/tap/covise. I am running MacOS 11.1 Bug Sur and latest stable Xcode from AppStore.

Looks like dependencies are installed, and the error happens while building covise. 

I am attaching complete terminal output. Maybe it looks a bit messy. If you need any additional details, I would be glad to provide it. Thank you for any help.
[Terminal_output.txt](https://github.com/hlrs-vis/covise/files/5740284/Terminal_output.txt)

**Comment by aumuell** [comment]
I can only guess what went wrong from the Terminal_output.txt: probably the version from Sept 2020 does not compile against VTK 9. You should be able to work around this with `brew install --HEAD covise`.

If this does not fix it, please include the log files from `~/Library/Logs/Homebrew/covise/`.

**Comment by kairzhanable** [comment]
> I can only guess what went wrong from the Terminal_output.txt: probably the version from Sept 2020 does not compile against VTK 9. You should be able to work around this with `brew install --HEAD covise`.
> 
> If this does not fix it, please include the log files from `~/Library/Logs/Homebrew/covise/`.

Thank you for your help! I removed traces of an old installation and all dependencies and ran `brew install --HEAD covise`. It did the trick, now everything seems to be in a working condition.
